periodics:
- name: ci-kubernetes-e2e-kubeadm-kind-master
  interval: 1h
  decorate: true
  labels:
    preset-bazel-scratch-dir: "true"
    preset-bazel-remote-cache-enabled: "true"
    preset-dind-enabled: "true"
  decoration_config:
    timeout: 2400000000000 #40m
  extra_refs:
  - org: kubernetes
    repo: kubernetes
    base_ref: master
    path_alias: k8s.io/kubernetes
  - org: kubernetes
    repo: kubeadm
    base_ref: master
    path_alias: k8s.io/kubeadm
  - org: kubernetes-sigs
    repo: kind
    base_ref: master
    path_alias: sigs.k8s.io/kind
  spec:
    containers:
    - image: gcr.io/k8s-testimages/kubekins-e2e:latest-master
      imagePullPolicy: Always
      env:
      # for bazel caching
      - name: REPO_OWNER
        value: kubernetes
      - name: REPO_NAME
        value: kubernetes
      command:
      - kubetest
      args:
      - --build=bazel
      - --provider=skeleton
      - --deployment=kind
      - --kind-binary-version=build
      - --kind-config-path=./../../k8s.io/kubeadm/tests/e2e/kind/single-cp/single-cp.yaml
      - --test
      - --check-version-skew=false
      # TODO(bentheelder): num-nodes in particular is brittle. it would be better for kubetest to handle this
      - --test_args=--ginkgo.focus=\[Conformance\] --ginkgo.skip=\[Serial\]|Alpha|Kubectl|\[(Disruptive|Feature:[^\]]+|Flaky)\] --disable-log-dump=true --num-nodes=3
      - --ginkgo-parallel
      - --timeout=30m
      # we need privileged mode in order to do docker in docker
      securityContext:
        privileged: true
      # kind needs /lib/modules and cgroups from the host
      volumeMounts:
      - mountPath: /lib/modules
        name: modules
        readOnly: true
      - mountPath: /sys/fs/cgroup
        name: cgroup
      resources:
        requests:
          # these are both a bit below peak usage during build
          # this is mostly for building kubernetes
          memory: "9000Mi"
          # during the tests more like 3-20m is used
          cpu: 2000m
    volumes:
    - name: modules
      hostPath:
        path: /lib/modules
        type: Directory
    - name: cgroup
      hostPath:
        path: /sys/fs/cgroup
        type: Directory
