# package tests
periodics:
- name: periodic-kubernetes-e2e-packages-pushed
  interval: 24h
  decorate: true
  extra_refs:
  - org: kubernetes
    repo: kubeadm
    base_ref: master
    path_alias: k8s.io/kubeadm
  spec:
    containers:
    -  image: gcr.io/k8s-testimages/kubekins-e2e:latest-master
       imagePullPolicy: Always
       command:
       - ./tests/e2e/packages/verify_packages_published.sh

- name: periodic-kubernetes-e2e-packages-install-deb
  interval: 24h
  decorate: true
  extra_refs:
  - org: kubernetes
    repo: kubeadm
    base_ref: master
    path_alias: k8s.io/kubeadm
  spec:
    containers:
    -  image: gcr.io/k8s-testimages/kubekins-e2e:latest-master
       imagePullPolicy: Always
       command:
       - ./tests/e2e/packages/verify_packages_install_deb.sh
