periodics:
# This is a sig-release-master-blocking job.
- cron: '1 3 * * 1,2,3,4,5' # Run at 19:01PST on Sun-Thu (03:01 UTC on Mon-Fri)
  name: ci-kubernetes-e2e-gce-scale-correctness
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
    preset-e2e-scalability-common: "true"
  spec:
    containers:
    - args:
      - --timeout=240
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --cluster=gce-scale-cluster
      - --env=HEAPSTER_MACHINE_TYPE=n1-standard-32
      - # TODO(mm4tt): Set it everywhere once it's confirmed to be working.
      - --env=LOG_DUMP_SYSTEMD_JOURNAL=true
      - --extract=ci/latest
      - --gcp-master-image=gci
      - --gcp-node-image=gci
      - --gcp-node-size=g1-small
      - --gcp-nodes=5000
      - --gcp-project=kubernetes-scale
      - --gcp-zone=us-east1-b
      - --ginkgo-parallel=40
      - --provider=gce
      - --test_args=--ginkgo.flakeAttempts=2 --ginkgo.skip=\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\]|\[DisabledForLargeClusters\] --minStartupPods=8 --node-schedulable-timeout=90m
      - --timeout=210m
      - --use-logexporter
      image: gcr.io/k8s-testimages/kubekins-e2e:v20190211-76e197f51-master
      resources:
        requests:
          cpu: 6
          memory: "16Gi"

# This is a sig-release-master-blocking job.
- cron: '1 8 * * 1,2,3,4,5' # Run at 00:01PST (8:01 UTC) on Mon, Thu, Wed, Thu and Fri
  name: ci-kubernetes-e2e-gce-scale-performance
  tags:
  - "perfDashPrefix: gce-5000Nodes"
  - "perfDashJobType: performance"
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
    preset-e2e-scalability-common: "true"
  spec:
    containers:
    - args:
      - --timeout=1080
      - --repo=k8s.io/kubernetes=master
      - --repo=k8s.io/perf-tests=master
      - --root=/go/src
      - --scenario=kubernetes_e2e
      - --
      - --cluster=gce-scale-cluster
      - --env=HEAPSTER_MACHINE_TYPE=n1-standard-32
      - --extract=ci/latest
      - --gcp-nodes=5000
      - --gcp-project=kubernetes-scale
      - --gcp-zone=us-east1-b
      - --provider=gce
      - --test=false
      - --test-cmd=$GOPATH/src/k8s.io/perf-tests/run-e2e.sh
      - --test-cmd-args=cluster-loader2
      - --test-cmd-args=--nodes=5000
      - --test-cmd-args=--provider=gce
      - --test-cmd-args=--report-dir=/workspace/_artifacts
      - --test-cmd-args=--testconfig=testing/density/config.yaml
      - --test-cmd-args=--testconfig=testing/load/config.yaml
      - --test-cmd-args=--testoverrides=./testing/density/5000_nodes/override.yaml
      - --test-cmd-name=ClusterLoaderV2
      - --timeout=1050m
      - --use-logexporter
      image: gcr.io/k8s-testimages/kubekins-e2e:v20190211-76e197f51-master
      resources:
        requests:
          cpu: 6
          memory: "16Gi"

- interval: 30m
  name: ci-kubernetes-e2e-gci-gce-scalability
  tags:
  - "perfDashPrefix: gce-100Nodes"
  - "perfDashJobType: performance"
  - "perfDashBuildsCount: 500"
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
    preset-e2e-scalability-common: "true"
  spec:
    containers:
    - image: gcr.io/k8s-testimages/kubekins-e2e:v20190211-76e197f51-master
      args:
      - --timeout=140
      - --repo=k8s.io/kubernetes=master
      - --repo=k8s.io/perf-tests=master
      - --root=/go/src
      - --scenario=kubernetes_e2e
      - --
      - --check-leaked-resources
      - --cluster=e2e-big
      - --extract=ci/latest
      - --gcp-node-image=gci
      - --gcp-nodes=100
      - --gcp-project-type=scalability-project
      - --gcp-zone=us-east1-b
      - --provider=gce
      - --test=false
      - --test-cmd=$GOPATH/src/k8s.io/perf-tests/run-e2e.sh
      - --test-cmd-args=cluster-loader2
      - --test-cmd-args=--nodes=100
      - --test-cmd-args=--provider=gce
      - --test-cmd-args=--report-dir=/workspace/_artifacts
      - --test-cmd-args=--testconfig=testing/density/config.yaml
      - --test-cmd-args=--testconfig=testing/load/config.yaml
      - --test-cmd-args=--testoverrides=./testing/density/100_nodes/override.yaml
      - --test-cmd-name=ClusterLoaderV2
      - --timeout=120m
      - --use-logexporter

# This is a sig-release-<beta>-blocking job.
- cron: "0 */6 * * *" # every six hours
  name: ci-kubernetes-e2e-gci-gce-scalability-beta
  tags:
  - "perfDashPrefix: gce-100Nodes-beta"
  - "perfDashJobType: performance"
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
    preset-e2e-scalability-common: "true"
  spec:
    containers:
    - args:
      - --timeout=140
      - --repo=k8s.io/kubernetes=master
      - --repo=k8s.io/perf-tests=master
      - --root=/go/src
      - --scenario=kubernetes_e2e
      - --
      - --cluster=e2e-big-beta
      - --extract=ci/k8s-beta
      - --gcp-node-image=gci
      - --gcp-nodes=100
      - --gcp-project-type=scalability-project
      - --gcp-zone=us-east1-b
      - --provider=gce
      - --test=false
      - --test-cmd=$GOPATH/src/k8s.io/perf-tests/run-e2e.sh
      - --test-cmd-args=cluster-loader2
      - --test-cmd-args=--nodes=100
      - --test-cmd-args=--provider=gce
      - --test-cmd-args=--report-dir=/workspace/_artifacts
      - --test-cmd-args=--testconfig=testing/density/config.yaml
      - --test-cmd-args=--testconfig=testing/load/config.yaml
      - --test-cmd-args=--testoverrides=./testing/density/100_nodes/override.yaml
      - --test-cmd-name=ClusterLoaderV2
      - --timeout=120m
      - --use-logexporter
      image: gcr.io/k8s-testimages/kubekins-e2e:v20190211-76e197f51-master

# This is a sig-release-<stable1>-blocking job.
- cron: "0 0/12 * * *" # every six hours, disjoint with ci-kubernetes-e2e-gci-gce-scalability-stable2 and ci-kubernetes-e2e-gci-gce-scalability-stable3
  name: ci-kubernetes-e2e-gci-gce-scalability-stable1
  tags:
  - "perfDashPrefix: gce-100Nodes-stable1"
  - "perfDashJobType: performance"
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
    preset-e2e-scalability-common: "true"
  spec:
    containers:
    - args:
      - --timeout=140
      - --repo=k8s.io/kubernetes=master
      - --repo=k8s.io/perf-tests=master
      - --root=/go/src
      - --scenario=kubernetes_e2e
      - --
      - --cluster=e2e-big-stable1
      # Use default kube-qps and kube-api-burst flag values.
      - --env=CONTROLLER_MANAGER_TEST_ARGS=--profiling
      - --env=SCHEDULER_TEST_ARGS=--profiling
      - --extract=ci/k8s-stable1
      - --gcp-node-image=gci
      - --gcp-nodes=100
      - --gcp-project-type=scalability-project
      - --gcp-zone=us-east1-b
      - --provider=gce
      - --test=false
      - --test-cmd=$GOPATH/src/k8s.io/perf-tests/run-e2e.sh
      - --test-cmd-args=cluster-loader2
      - --test-cmd-args=--nodes=100
      - --test-cmd-args=--provider=gce
      - --test-cmd-args=--report-dir=/workspace/_artifacts
      - --test-cmd-args=--testconfig=testing/density/config.yaml
      - --test-cmd-args=--testconfig=testing/load/config.yaml
      - --test-cmd-args=--testoverrides=./testing/density/100_nodes/override.yaml
      - --test-cmd-name=ClusterLoaderV2
      - --timeout=120m
      - --use-logexporter
      image: gcr.io/k8s-testimages/kubekins-e2e:v20190211-76e197f51-master

# This is a sig-release-<stable2>-blocking job.
- cron: "0 4-16/12 * * *" # every six hours, disjoint with ci-kubernetes-e2e-gci-gce-scalability-stable1 and ci-kubernetes-e2e-gci-gce-scalability-stable3
  name: ci-kubernetes-e2e-gci-gce-scalability-stable2
  tags:
  - "perfDashPrefix: gce-100Nodes-stable2"
  - "perfDashJobType: performance"
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
    preset-e2e-scalability-common: "true"
  spec:
    containers:
    - args:
      - --timeout=140
      - --repo=k8s.io/kubernetes=master
      - --repo=k8s.io/perf-tests=master
      - --root=/go/src
      - --scenario=kubernetes_e2e
      - --
      - --cluster=e2e-big-stable2
      # Use default kube-qps and kube-api-burst flag values.
      - --env=CONTROLLER_MANAGER_TEST_ARGS=--profiling
      - --env=SCHEDULER_TEST_ARGS=--profiling
      - --extract=ci/k8s-stable2
      - --gcp-node-image=gci
      - --gcp-nodes=100
      - --gcp-project-type=scalability-project
      - --gcp-zone=us-east1-b
      - --provider=gce
      - --test=false
      - --test-cmd=$GOPATH/src/k8s.io/perf-tests/run-e2e.sh
      - --test-cmd-args=cluster-loader2
      - --test-cmd-args=--nodes=100
      - --test-cmd-args=--provider=gce
      - --test-cmd-args=--report-dir=/workspace/_artifacts
      - --test-cmd-args=--testconfig=testing/density/config.yaml
      - --test-cmd-args=--testconfig=testing/load/config.yaml
      #TODO: Add resource constraints when stable2 >= 1.12
      - --test-cmd-name=ClusterLoaderV2
      - --timeout=120m
      - --use-logexporter
      image: gcr.io/k8s-testimages/kubekins-e2e:v20190211-76e197f51-master

# This is a sig-release-<stable3>-blocking job.
- cron: "0 8-20/12 * * *" # every six hours, disjoint with ci-kubernetes-e2e-gci-gce-scalability-stable1 and ci-kubernetes-e2e-gci-gce-scalability-stable2
  name: ci-kubernetes-e2e-gci-gce-scalability-stable3
  tags:
  - "perfDashPrefix: gce-100Nodes-stable3"
  - "perfDashJobType: performance"
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
    preset-e2e-scalability-common: "true"
  spec:
    containers:
    - args:
      - --timeout=140
      - --repo=k8s.io/kubernetes=master
      - --repo=k8s.io/perf-tests=master
      - --root=/go/src
      - --scenario=kubernetes_e2e
      - --
      - --cluster=e2e-big-stable2
      # Use default kube-qps and kube-api-burst flag values.
      - --env=CONTROLLER_MANAGER_TEST_ARGS=--profiling
      - --env=SCHEDULER_TEST_ARGS=--profiling
      - --extract=ci/k8s-stable3
      - --gcp-node-image=gci
      - --gcp-nodes=100
      - --gcp-project-type=scalability-project
      - --gcp-zone=us-east1-b
      - --provider=gce
      - --test=false
      - --test-cmd=$GOPATH/src/k8s.io/perf-tests/run-e2e.sh
      - --test-cmd-args=cluster-loader2
      - --test-cmd-args=--nodes=100
      - --test-cmd-args=--provider=gce
      - --test-cmd-args=--report-dir=/workspace/_artifacts
      - --test-cmd-args=--testconfig=testing/density/config.yaml
      - --test-cmd-args=--testconfig=testing/load/config.yaml
      #TODO: Add resource constraints when stable3 >= 1.12
      - --test-cmd-name=ClusterLoaderV2
      - --timeout=120m
      - --use-logexporter
      image: gcr.io/k8s-testimages/kubekins-e2e:v20190211-76e197f51-master
