presubmits:
  kubernetes-sigs/aws-ebs-csi-driver:
  - name: pull-aws-ebs-csi-driver-verify
    always_run: true
    decorate: true
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20190214-f4092ae69-master
        command:
        - runner.sh
        args:
        - make
        - verify
  - name: pull-aws-ebs-csi-driver-unit
    always_run: true
    decorate: true
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20190214-f4092ae69-master
        command:
        - runner.sh
        args:
        - make
        - test
  - name: pull-aws-ebs-csi-driver-sanity
    always_run: true
    decorate: true
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20190214-f4092ae69-master
        command:
        - runner.sh
        args:
        - make
        - test-sanity
  - name: pull-aws-ebs-csi-driver-integration
    always_run: true
    decorate: true
    labels:
      preset-service-account: "true"
      preset-aws-credential-aws-oss-testing: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20190214-f4092ae69-master
        command:
        - runner.sh
        args:
        - make
        - test-integration
  - name: pull-aws-ebs-csi-driver-e2e-single-az
    always_run: true
    decorate: true
    labels:
      preset-service-account: "true"
      preset-dind-enabled: "true"
      preset-aws-credential-aws-oss-testing: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20190214-f4092ae69-master
        command:
        - runner.sh
        args:
        - make
        - test-e2e-single-az
        securityContext:
          privileged: true
  - name: pull-aws-ebs-csi-driver-e2e-multi-az
    always_run: true
    decorate: true
    labels:
      preset-service-account: "true"
      preset-dind-enabled: "true"
      preset-aws-credential-aws-oss-testing: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20190214-f4092ae69-master
        command:
        - runner.sh
        args:
        - make
        - test-e2e-multi-az
        securityContext:
          privileged: true
