periodics:
- name: ci-kubernetes-e2e-windows-gce-poc
  decorate: true
  extra_refs:
  - org: pjh
    repo: kubernetes
    base_ref: windows-up
    path_alias: k8s.io/kubernetes
  - org: yujuhong
    repo: gce-k8s-windows-testing
    base_ref: master
    path_alias: k8s.io/gce-k8s-windows-testing
  - org: kubernetes
    repo: release
    base_ref: master
    path_alias: k8s.io/release
  interval: 2h
  labels:
    preset-k8s-ssh: "true"
    preset-service-account: "true"
    preset-bazel-scratch-dir: "true"
    preset-bazel-remote-cache-enabled: "true"
  spec:
    containers:
    - command:
      - runner.sh
      - /workspace/scenarios/kubernetes_e2e.py
      args:
      - --check-leaked-resources
      - --cluster=
      - --build=bazel
      - --stage=gs://kubernetes-release-dev/ci/ci-kubernetes-e2e-windows-gce-poc
      - --extract=local
      - --gcp-zone=us-west1-b
      - --ginkgo-parallel=8
      - --provider=gce
      - --test=false
      - --test-cmd=$GOPATH/src/k8s.io/gce-k8s-windows-testing/run-e2e.sh
      - --test-cmd-args=--ginkgo.focus=\[Conformance\] --minStartupPods=8
      - --timeout=120m
      env:
      - name: USE_RELEASE_NODE_BINARIES
        value: "true"
      - name: KUBE_GCE_ENABLE_IP_ALIASES
        value: "true"
      image: gcr.io/k8s-testimages/kubekins-e2e:v20190214-f4092ae69-master
      resources:
        requests:
          memory: "8Gi"

- name: ci-kubernetes-e2e-windows-gce
  decorate: true
  extra_refs:
  - org: yujuhong
    repo: gce-k8s-windows-testing
    base_ref: master
    path_alias: k8s.io/gce-k8s-windows-testing
  interval: 2h
  labels:
    preset-k8s-ssh: "true"
    preset-service-account: "true"
  spec:
    containers:
    - command:
      - runner.sh
      - /workspace/scenarios/kubernetes_e2e.py
      args:
      - --check-leaked-resources
      - --cluster=
      - --extract=ci-cross/latest
      - --gcp-zone=us-west1-b
      - --ginkgo-parallel=8
      - --provider=gce
      - --gcp-nodes=2
      - --test=false
      - --test-cmd=$GOPATH/src/k8s.io/gce-k8s-windows-testing/run-e2e.sh
      - --test-cmd-args=--ginkgo.focus=\[Conformance\] --minStartupPods=8
      - --timeout=120m
      env:
      - name: KUBE_GCE_ENABLE_IP_ALIASES
        value: "true"
      - name: NUM_WINDOWS_NODES
        value: "3"
      - name: KUBERNETES_NODE_PLATFORM
        value: "windows"
      image: gcr.io/k8s-testimages/kubekins-e2e:v20190214-f4092ae69-master
