periodics:
- interval: 1h
  name: maintenance-ci-aws-janitor
  labels:
    preset-service-account: "true"
  spec:
    containers:
    - args:
      - --bare
      - --timeout=60
      - --service-account=/etc/service-account/service-account.json
      - --upload=gs://kubernetes-jenkins/logs
      - --scenario=execute
      - --
      - /aws-janitor
      - --
      - --ttl=2h30m
      - --path=s3://k8s-kops-prow/objs.json
      env:
      - name: AWS_SHARED_CREDENTIALS_FILE
        value: /workspace/.aws/credentials
      image: gcr.io/k8s-test-infra-aws/aws-janitor:v20190114-57d0fe238
      volumeMounts:
      - mountPath: /workspace/.aws
        name: aws-cred
        readOnly: true
    volumes:
    - name: aws-cred
      secret:
        defaultMode: 256
        secretName: aws-cred-new

- interval: 24h
  name: maintenance-ci-janitor
  labels:
    preset-service-account: "true"
  decorate: true
  extra_refs:
  - org: kubernetes
    repo: test-infra
    base_ref: master
    path_alias: k8s.io/test-infra
  spec:
    containers:
    - command:
      - runner.sh
      args:
      - go
      - run
      - experiment/ci-janitor/main.go
      - --config-path=prow/config.yaml
      - --job-config-path=config/jobs
      - --janitor-path=boskos/janitor/janitor.py
      image: gcr.io/k8s-testimages/kubekins-e2e:v20190211-76e197f51-master
      resources:
        requests:
          cpu: 5
          memory: "8Gi"

- interval: 1h
  name: maintenance-pull-janitor
  labels:
    preset-service-account: "true"
  spec:
    containers:
    - args:
      - --bare
      - --timeout=30
      - --service-account=/etc/service-account/service-account.json
      - --upload=gs://kubernetes-jenkins/logs
      - --scenario=kubernetes_janitor
      - --
      - --mode=pr
      env:
      image: gcr.io/k8s-testimages/kubekins-e2e:v20190211-76e197f51-experimental
      resources:
        requests:
          cpu: 5
          memory: "8Gi"

- interval: 1h
  name: maintenance-pull-scale-janitor
  labels:
    preset-service-account: "true"
  spec:
    containers:
    - args:
      - --bare
      - --timeout=60
      - --service-account=/etc/service-account/service-account.json
      - --upload=gs://kubernetes-jenkins/logs
      - --scenario=kubernetes_janitor
      - --
      - --mode=scale
      - --ratelimit=5
      env:
      image: gcr.io/k8s-testimages/kubekins-e2e:v20190211-76e197f51-experimental
      resources:
        requests:
          cpu: 5
          memory: "8Gi"
